server:
  port: 8887

github:
  client:
    id: 7e17d0682cdeb283af67
    secret: bc33a643bda0c8e921f210dff71630a5efec3cb9
  redirect:
    uri: http://localhost:${server.port}/callback

spring:
  datasource:
    url: jdbc:h2:F:\github\community
    username: sa
    password: 123
    driver-class-name: org.h2.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
